baseURL = "/"
languageCode = "en-us"
title = "CodeHealth"

pygmentsUseClasses = true
pygmentsCodefences = true

[markup.highlight]
      codeFences = true
      guessSyntax = true
      tabWidth = 4
      noClasses = false
      style = "github-light"

[markup.goldmark.renderer]
unsafe= true

[params]
      featuredPosts = [
            "/posts/avoid-nested-conditionals.md", 
            "/posts/simplify-long-list-of-parameters.md",
      ]
      test = true