baseURL = "/"
languageCode = "en-us"
title = "CodeHealth"
paginate = 10

disableKinds = ['taxonomy', 'term']
[taxonomies]
  tags = ""
  categories = ""

pygmentsUseClasses = true
pygmentsCodefences = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      tabWidth = 4
      noClasses = false
      style = "github-light"

[markup.goldmark.renderer]
unsafe= true

